### ISSUE TITLE
Resource compiler is not necessarily named "rcc"

### ISSUE THREAD

**Issue by adam-lavrik** [Peterkmoss/qMarkdown#20]
`rcc` utility name can vary, e. g. on Fedora it's named `rcc-qt5` (for Qt 5). That's why hardcoded `rcc` command for generating resource file with images fails, and no images are displayed.

**Comment by Peterwmoss** [comment]
Looking into this, if you install the latest version of the `qt-devel` package on fedora (tested on Fedora Workspace 37), the binary is called `rcc`. 

I think that it will be difficult do take into account what the older versions of the resource compiler binary files will be called on different distributions.

That being said, I'll look into other ways of getting images displayed as currently it's very clunky anyways

**Comment by adam-lavrik** [comment]
Well, I have Fedora 37 with Qt 5.15 and qt-devel 4.8.7. I think that you're right, and images should be supported in different way.

By the way, have you tested this app in Windows? Here are some `sh` commands hardcoded, I'm not sure they will work properly in Windows shell. (I replaced `rm` commands with `QFile::remove` in my pull request).

**Comment by Peterwmoss** [comment]
I'm looking into a way of not having to use `rcc` on runtime and only need it on compiletime.

I have not tested the software on windows yet, no, but using Qt's tools to remove files etc. should help with this.

In the way I'm hoping to eliminate the use of `rcc` there should no longer be any more shell commands within the code.

**Comment by Peterwmoss** [comment]
I've merged the refactoring that you have done and in the process I have ensured that the RCC compiler is no longer used at all. So far in my testing it has worked, but it could behave differently based on OS.

I'll close this issue. If you want to create an issue on the Windows aspect feel free to do so, so we can keep the topics separate.

Thanks again for your contribution.
